### ISSUE TITLE
Stardew Valley 

### ISSUE THREAD

**Issue by MariusGGS** [CubeCoders/AMPTemplates#704]
# Module Request

Note: Please try setting up a configuration yourself before raising an issue to request a configuration:  ~~https://config.getamp.sh/~~
***There is a newer beta version available at https://iceofwraith.github.io/GenericConfigGen/

## Game Information:

Game Title: Stardew Valley
How to obtain: https://github.com/ObjectManagerManager/SMAPIDedicatedServerMod or https://github.com/Chris82111/SMAPIDedicatedServerMod 
Suppoted OSs: Windows, Linux 
Supports RCON/Console input?

## I confirm:

- [x] that I have searched for an existing module request for this application.
- [ ] that the server is an official server distributed by the games publishers/developers.
- [x] that the server is available to the general public.
- [x] that the server can be run headless (without a GUI).
- [ ] I have already attempted to create a configuration myself using the configuration tool
- [x] that my checkboxes above look like the one on the left (remove this line when done)

**Comment by Greelan** [comment]
Mod hasn't been updated for v1.6 of the game yet

**Comment by Greelan** [comment]
I have a draft template in my dev branch  `Greelan/AMPTemplates:dev` - that  needs testing.

**Comment by EcchiNemi** [comment]
I'm getting the following error when starting the server:

[SMAPI] SMAPI 4.0.8 with Stardew Valley 1.6.8 build 24119 on Unix 6.1.0.21
[SMAPI] Mods go here: /home/amp/.ampdata/instances/StardewValleyVE-Server01/stardew-valley/server/Mods
[SMAPI] Waiting for game to launch...
[game] The game failed to launch: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device!
---> NullReferenceException: Object reference not set to an instance of an object.
at MonoGame.OpenGL.GL.LoadExtensions() in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\Graphics\OpenGL.cs:line 1443
at MonoGame.OpenGL.GraphicsContext..ctor(IWindowInfo info) in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\Graphics\GraphicsContext.SDL.cs:line 49
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup() in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\Graphics\GraphicsDevice.OpenGL.cs:line 249
at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup() in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 297
at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, Boolean preferHalfPixelOffset, PresentationParameters presentationParameters) in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Graphics\GraphicsDevice.cs:line 273
at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi) in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\GraphicsDeviceManager.cs:line 144
at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice() in D:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\GraphicsDeviceManager.cs:line 115
--- End of inner exception stack trace ---

Any idea what the problem could be?
I'm running AMP on Proxmox using Debian.

Thanks in advance for the help <3

**Comment by Greelan** [comment]
Yeah, it sux. Coz it's just the game client running, it wants a GPU

**Comment by EcchiNemi** [comment]
Sorry for the late reply and thanks for your info ^-^
Adding a GPU fixed the error but now the Instance is stuck at "Starting Stardew Valley":

[SMAPI] Found 2 mods with warnings:
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.
[SMAPI]       - Server Port Changer 1.0.0 because it's no longer compatible. Please check for a new version at https://smapi.io/mods
[SMAPI]    Bypassed safety checks
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods bypass SMAPI's normal safety checks, so they're more likely to cause errors or save
[SMAPI]       corruption. If your game has issues, try removing these first.
[SMAPI]       - Always On Server
[SMAPI] Launching mods...
[SMAPI] Mods loaded and ready!
[game] Oops! Steam achievements won't work because Steam isn't loaded. See 'Configure your game client' in the install guide for more info: https://smapi.io/install.
[SMAPI] Type 'help' for help, or 'help <cmd>' for a command's usage

Is it because of the Server Port Changer?
On the SMAPI website it says it's compatible though.

**Comment by BroOtti** [comment]
From the mod page of Server Port Changer:

> COMPATIBILITY
> This should be compatible with any mod that doesn't also happen to change the port that the server is hosted on.
> It was built for Stardew Valley 1.3.28 & SMAPI 2.7, it has not yet been tested with SMAPI 2.8.

It probably needs an update. Current latest version of SMAPI is 4.0.8

**Comment by Greelan** [comment]
The whole thing is a mess atm

**Comment by christmaswreath** [comment]
bump
