### ISSUE TITLE
Eco v11 upcoming update changes

### ISSUE THREAD

**Issue by AWL-Gaming** [CubeCoders/AMPTemplates#932]
Add the new -username="" -password="" arguments (or custom commands support) to the Eco server template. Currently the upcoming major update compatibility is still not implemented, resulting in the following errors upon server startup:

```properties
[11:20:57] Failed to start the server. Exception was Exception: Exception
Message:Authentication to Strange Cloud failed. No authentication methods were available. Provide valid credentials ('-username' and '-password' or '-userToken' or '-steamTicket') or use '-offline' to start server in offline mode.
Source:EcoServer
System.Exception: Authentication to Strange Cloud failed. No authentication methods were available. Provide valid credentials ('-username' and '-password' or '-userToken' or '-steamTicket') or use '-offline' to start server in offline mode.
at Eco.Server.StrangeCloudLogin.Initialize()
at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
[11:20:57] Shutdown finished
```

**Comment by Greelan** [comment]
Will be added shortly

**Comment by Greelan** [comment]
Now added. Let me know if any tweaks needed. Couldn't actually find any info on these online based on a very quick search

**Comment by AWL-Gaming** [comment]
> Now added. Let me know if any tweaks needed. Couldn't actually find any info on these online based on a very quick search

Facing the following issue:
```properties
Failed to start the server. Exception was Exception: Exception
Message:Authentication to Strange Cloud failed. No authentication methods were available. Provide valid credentials ('-username' and '-password' or '-userToken' or '-steamTicket') or use '-offline' to start server in offline mode.
Source:EcoServer
System.Exception: Authentication to Strange Cloud failed. No authentication methods were available. Provide valid credentials ('-username' and '-password' or '-userToken' or '-steamTicket') or use '-offline' to start server in offline mode.
at Eco.Server.StrangeCloudLogin.Initialize()
at Eco.Server.PluginManager.InitializeAsync(StartupInfo startupInfo)
at Eco.Server.Startup.StartAsync(StartupInfo startupInfo)
: 1
23:08:22
[12:08:22] Argument 'username' has to be passed with a value using the following format: -username="value"
[12:08:22] Argument 'password' has to be passed with a value using the following format: -password="value"
```

**Comment by AWL-Gaming** [comment]
Fixed, correct syntax would be: "AuthMode":"-username**=**\"{{AuthUsername}}\" -password**=**\"{{AuthPassword}}\"",
This can be closed whenever the new changes get pushed into the repo for Eco.

**Comment by Greelan** [comment]
Check the Support and Updates tab, that's the format that is specified in the template

**Comment by Greelan** [comment]
Ah, it needs =
